// Fuentes (issue #137): referencias públicas de la información que usa la app, por tema, con su estado honesto.
// Una referencia aquí NO significa que Pablo haya validado el valor ni que la app lo aplique tal cual: los gramajes y recetas son de EJEMPLO.
// Estados: «publicada» (artículo, guía o consenso público, enlace comprobado por Instinct), «doi_aportado» (DOI recogido, aún sin abrir),
// «criterio_pablo» (decisión profesional de Pablo, no es un estudio), «dato_ejemplo» (cifra de ejemplo sin validar).
// Informes nuevos añaden aquí sus referencias (con DOI o URL real, nunca inventados).
window.FUENTES = [
  { tema: 'Energía, calorías y disponibilidad energética', referencia: 'Mountjoy et al., IOC consensus statement on REDs (2023)', enlace: 'https://bjsm.bmj.com/content/57/17/1073', respalda: 'Vigilar la baja disponibilidad energética; evitar reglas automáticas que produzcan infraalimentación. La app no diagnostica.', estado: 'publicada' },
  { tema: 'Hidratos, carga y competición', referencia: 'Burke et al., Carbohydrates for training and competition (2011)', enlace: 'https://pubmed.ncbi.nlm.nih.gov/21660838/', respalda: 'Periodización de hidratos según entrenamiento y competición. Las guías sitúan la carga en pruebas de más de 90 min.', estado: 'publicada' },
  { tema: 'Hidratos, carga y competición', referencia: 'Thomas, Erdman y Burke, Nutrition and Athletic Performance (ACSM/AND/DC, 2016)', enlace: 'https://www.vevu.hr/upload/kol_33/50Nutrition_and_Athletic_Performance.pdf', respalda: 'Bandas de hidratos para carga, antes, durante y después. Bandas condicionales, no dosis automáticas por deporte.', estado: 'publicada' },
  { tema: 'Hidratos, carga y competición', referencia: 'IOC, Nutrition for Athletes (guía)', enlace: 'https://stillmed.olympic.org/media/Document%20Library/OlympicOrg/IOC/Who-We-Are/Commissions/Medical-and-Scientific-Commission/EN-Nutrition-for-Athletes.pdf', respalda: 'Recuperación: 5–7 g/kg en esfuerzo moderado y 7–12 g/kg en moderado-intenso. Guía antigua; no fija topes por alimento.', estado: 'publicada' },
  { tema: 'Hidratos, carga y competición', referencia: 'Umbral de carga completa: más de 150 min continuos', enlace: '', respalda: 'Decisión de Pablo (05/10/2026), no un resultado de estudio. Las guías de consenso sitúan la carga de hidratos en pruebas de más de 90 min.', estado: 'criterio_pablo' },
  { tema: 'Fibra y comodidad digestiva', referencia: 'Fibre: The Forgotten Carbohydrate in Sports Nutrition Recommendations (2025)', enlace: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC12106500/', respalda: 'Comodidad gastrointestinal y fibra cerca del ejercicio; evidencia limitada de manipular la fibra. No define gramos máximos de alimento.', estado: 'publicada' },
  { tema: 'Proteína', referencia: 'Jäger et al., ISSN position stand: protein and exercise (2017)', enlace: 'https://link.springer.com/article/10.1186/s12970-017-0177-8', respalda: 'Proteína de 1,4–2,0 g/kg/día en personas que entrenan; depende de la energía y del estado individual.', estado: 'publicada' },
  { tema: 'Proteína', referencia: 'ISSN position stand: nutrient timing (2017)', enlace: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC5596471/', respalda: '20–40 g de proteína por toma y tomas cada ~3 h, de forma orientativa; sin mínimo obligatorio de comidas.', estado: 'publicada' },
  { tema: 'Líquidos y sodio', referencia: 'NATA position statement: Fluid Replacement for the Physically Active (2017)', enlace: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC5634236/', respalda: 'Evitar hipo e hiperhidratación; sodio individual. No promete prevenir la hiponatremia con sodio.', estado: 'publicada' },
  { tema: 'Deportes concretos', referencia: 'UEFA expert group statement on nutrition in elite football (2021)', enlace: 'https://bjsm.bmj.com/content/55/8/416', respalda: 'Pauta de partido en fútbol de élite; no se extrapola automáticamente a todos los equipos.', estado: 'publicada' },
  { tema: 'Deportes concretos', referencia: 'ACSM expert consensus on weight loss in weight-category sports (2021)', enlace: 'https://journals.lww.com/acsm-csmr/fulltext/2021/04000/acsm_expert_consensus_statement_on_weight_loss_in.7.aspx', respalda: 'Riesgos del corte rápido, pesaje y recuperación. La app no calcula nada en deportes con categoría de peso.', estado: 'publicada' },
  { tema: 'Deportes concretos', referencia: 'Helms et al., natural bodybuilding contest preparation (2014)', enlace: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC4033492/', respalda: 'Composición corporal en culturismo; ámbito muy específico, no aplicable a estética general.', estado: 'publicada' },
  { tema: 'Deportes concretos', referencia: 'Systematic review of CrossFit workouts and dietary interventions (2021)', enlace: 'https://pubmed.ncbi.nlm.nih.gov/33513565/', respalda: 'Hay poca evidencia específica para CrossFit: no avala una tabla universal de macros.', estado: 'publicada' },
  { tema: 'Deportes concretos', referencia: 'Scoping review of dancers’ energy status and diets (2024)', enlace: 'https://www.mdpi.com/2072-6643/16/24/4293', respalda: 'Riesgos nutricionales en danza; no extrapolar cifras de élite a la población general.', estado: 'publicada' },
  { tema: 'Volumen, densidad y saciedad', referencia: 'Bell et al. (1998), Am J Clin Nutr 67(3):412', enlace: 'https://doi.org/10.1093/ajcn/67.3.412', respalda: 'Se come un peso de comida parecido aunque cambie la densidad calórica.', estado: 'doi_aportado' },
  { tema: 'Volumen, densidad y saciedad', referencia: 'Rolls y Bell (1999), Eur J Clin Nutr', enlace: 'https://doi.org/10.1038/sj.ejcn.1600757', respalda: 'Se come un peso de comida parecido aunque cambie la densidad calórica.', estado: 'doi_aportado' },
  { tema: 'Volumen, densidad y saciedad', referencia: 'Kral et al. (2004), Am J Clin Nutr 79(6):962', enlace: 'https://doi.org/10.1093/ajcn/79.6.962', respalda: 'Densidad energética y tamaño de ración actúan por separado y se suman.', estado: 'doi_aportado' },
  { tema: 'Volumen, densidad y saciedad', referencia: 'Geliebter et al. (1988), Physiol Behav', enlace: 'https://doi.org/10.1016/0031-9384(88)90333-2', respalda: 'La capacidad del estómago varía mucho entre personas.', estado: 'doi_aportado' },
  { tema: 'Volumen, densidad y saciedad', referencia: 'Geliebter y Hashim (2001), Physiol Behav', enlace: 'https://doi.org/10.1016/s0031-9384(01)00619-9', respalda: 'La capacidad del estómago varía mucho entre personas.', estado: 'doi_aportado' },
  { tema: 'Volumen, densidad y saciedad', referencia: 'Morilla-Herrera et al. (2016), J Nutr Health Aging', enlace: 'https://doi.org/10.1007/s12603-015-0591-z', respalda: 'Concentrar la comida sube la energía y la proteína ingeridas con poco apetito.', estado: 'doi_aportado' },
  { tema: 'Volumen, densidad y saciedad', referencia: 'Geny et al. (2023), Front Nutr', enlace: 'https://doi.org/10.3389/fnut.2023.1232502', respalda: 'Concentrar la comida sube la energía y la proteína ingeridas con poco apetito.', estado: 'doi_aportado' },
  { tema: 'Volumen, densidad y saciedad', referencia: 'Bandas de peso servido por nivel (−2 a +2)', enlace: '', respalda: 'Decisión de Pablo (05/10/2026): «me parecen bien las bandas». No son resultado de estudio.', estado: 'criterio_pablo' },
  { tema: 'Composición de los alimentos', referencia: 'USDA FoodData Central, SR Legacy (04/2018), dominio público', enlace: 'https://fdc.nal.usda.gov/', respalda: 'Kcal y macros del catálogo de recetas de ejemplo. Productos de EE. UU.; los hidratos incluyen la fibra. Algunos alimentos son equivalentes cercanos.', estado: 'publicada' },
  { tema: 'Raciones y cantidades', referencia: 'Raciones realistas, topes y mínimos por alimento y peso máximo de plato', enlace: '', respalda: 'Criterio profesional de Pablo (método propio); no es un estudio ni una guía pública.', estado: 'criterio_pablo' },
  { tema: 'Recetas y gramajes', referencia: 'Catálogo de recetas de EJEMPLO (115)', enlace: '', respalda: 'Gramajes, kcal y macros de ejemplo, pendientes de validar por Pablo.', estado: 'dato_ejemplo' },
];
